# Generated by Django 5.1 on 2024-09-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=25)),
                ('shop_no', models.IntegerField()),
                ('category', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
