# Generated by Django 5.1 on 2024-08-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=25)),
                ('roll', models.IntegerField()),
                ('section', models.CharField(max_length=2)),
                ('classname', models.CharField(max_length=24)),
            ],
        ),
    ]
